name: Linting Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm install --omit=dev

      - name: Check linting
        run: npm run lint
