name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --omit=dev

      - name: Run tests
        run: npm test